site_name: Портфоліо Загоруйко Денис

theme:
  name: material
  language: uk
  palette:
    primary: indigo
    accent: indigo
nav: 
  - 'Головна': 'index.md'
  - 'Про мене': 'about.md'
  - 'Мої проекти': 'projects.md'
  - 'Процес роботи': 'workflow.md'
